export enum LoadState {
    // MAIN
    FETCHING_MAIN_LOADLIST = 0,
    FETCHING_INDIVIDUAL_LOADLISTS = 1,

    // MATERIALS
    FETCHING_MATERIALS = 2,
    CONSTRUCTING_MATERIALS = 3,

    // MESHES
    FETCHING_MESHES = 4,
    CONSTRUCTING_MESHES = 5,

    // SHADERS
    FETCHING_SHADERS = 6,
    COMPILING_SHADERS = 7,

    FINISHED = 8
}