export enum LoadState {
    // MAIN
    FETCHING_MAIN_LOADLIST = 0,
    FETCHING_INDIVIDUAL_LOADLISTS = 1,

    // MATERIALS
    FETCHING_MATERIALS = 2,
    CONSTRUCTING_MATERIALS = 3,

    FINISHED = 4
}